### ISSUE TITLE
Support to open preview with Mou

### ISSUE THREAD

**Issue by agaviria** [kannokanno/previm#31]
Thanks for this wonderful vim markdown preview library.  Any chance you could include support for Mou?  This will help with the image [alt text] rendering for my markdown files which are not supported by browsers.  

    let g:previm_open_cmd = 'open -a Mou'

manages to open the Mou app but it seems to load an html file:

````<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <title>Preview</title>
        <link type="text/css" href="css/previm.css" rel="stylesheet" media="all" />
    </head>
    <body id="body">
        <div id="header">
            <span id="markdown-file-name">Loading...</span>
            <small><span id="last-modified"></span></small>
        </div>
        <div id="preview"></div>
        <div id="footer">
            <script src="js/lib/marked.min.js"></script>
            <script src="js/lib/highlight.pack.js"></script>
            <script src="js/lib/textile.js"></script>
            <script src="js/previm.js"></script>
            <div id="monitor"></div>
        </div>
    </body>
</html>````

Any suggestions on how I can fix this?

**Comment by agaviria** [comment]
Update: managed to render it by changing the suffix to .md.  However, it still fails to load resource (image).

**Comment by kannokanno** [comment]
Thank you for using previm.

## For Mou of support

I'm sorry, it can not be.
Because, previm be converted to markdown through javascript.
It is not possible to pass a markdown after conversion to other apps.

## Image [alt text] rendering

Is it not result to be expected in this writing?

If the absolute path(external link)

```markdown
![alt text](http://...)
```

If the relative path(local file)

```markdown
![alt text](foo/bar.png)
```

## I found a bug in the relative path

If you add a title to the image, it seems not go as expected.

If absolute path, it is converted in this way

```markdown
# markdown
![alt text](https://avatars2.githubusercontent.com/u/708123?v=3&s=96 "avatar")
```
```html
# html
<img src="https://avatars2.githubusercontent.com/u/708123?v=3&amp;s=96" alt="alt text" title="avatar">
```

But that's a relative path

```markdown
# markdown
![alt text](https://avatars2.githubusercontent.com/u/708123?v=3&s=96 "avatar")
```
```html
# html
<img src="file://localhost/Users/kanno/Pictures/profile.png%20&quot;avatar&quot;" alt="alt text">
```

This bug I had been to another issue.  #32

**Comment by agaviria** [comment]
Fair enough! Thank you.  I will look out for updates on issue #32.
